server:
  port: 8085

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ASHISH8340/EmployeeManagementSystem
          clone-on-start: true




