FROM openjdk:11
ADD ./target/medicine-list-Service-0.0.1-SNAPSHOT.jar /usr/src/medicine-list-Service-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar", "medicine-list-Service-0.0.1-SNAPSHOT.jar"]