services:
  mysqlservice:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USERNAME: 'root'

  eurekaserver:
    build: ./eurekaserver
    container_name: eureka-server
    restart: always
    network_mode: host
    hostname: localhost
    ports:
      - 8761:8761

  config:
    container_name: config
    build: ./config
    hostname: localhost
    network_mode: host
    restart: always
    depends_on:
      - eurekaserver
    ports:
      - 8888:8888

  apigateway:
    container_name: api-gateway
    build: ./apigateway
    hostname: localhost
    network_mode: host
    ports:
      - 8084:8084
    depends_on:
      - eurekaserver
    restart: always

  Employee:
    container_name: employee-service
    build: ./Employee
    hostname: localhost
    network_mode: host
    ports:
      - 8089:8089
    depends_on:
      - mysqlservice
      - eurekaserver
    restart: always


  Leave:
    container_name: leave-service
    build: ./Leave
    hostname: localhost
    network_mode: host
    ports:
      - 8086:8086
    depends_on:
      - mysqlservice
      - eurekaserver
    restart: always