server:
  port: 8084

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: User-Service
          uri: lb://User-Service
          predicates:
            - Path=/v1/api/**

        - id: GloQuoraPost-Service
          uri: lb://GloQuoraPost-Service
          predicates:
            - Path=/v1/api/**

        - id: AdminApp
          uri: lb://AdminApp
          predicates:
            - Path=/admin/**


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/