
spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888/
  main:
    allow-bean-definition-overriding: true
management:
  security:
    enabled: false







